# Generated by Django 3.2.4 on 2021-06-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210616_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select genre for this book', related_name='genres', to='catalog.Genre'),
        ),
    ]
